### ISSUE TITLE
tunneling doesn't seem to work

### ISSUE THREAD

**Issue by MadsRC** [cmp-202/ssh2shell#31]
I'm trying to connect to a host through another host, and I'm using the tunneltest.js file as a reference.

Here is my code:
```
var conParamsHost1 = {
  host:         'webmail.example.com',
  port:         22,
  userName:     'root',
  password:     'PASSWORD'
 }
var conParamsHost2 = {
  host:         'mail.example.com',
  port:         22,
  userName:     'user',
  password:     'PASSWORD'
 }

//Host objects:
var host1 = {
  server:              conParamsHost1,
  commands:            [
    'ls /'
  ],
  debug: true,
  connectedMessage:    "Connected to Primary host1",
  readyMessage:        "Running commands Now",
  closedMessage:       "Completed",
}

var host2 = {
  server:              conParamsHost2,
  commands:            [
    'whoami'
  ],
  debug: true,
  connectedMessage:    "Connected to host2",
  readyMessage:        "Running commands Now",
  closedMessage:       "Completed",
}

host1.hosts = [ host2 ];

//Create the new instance
var SSH2Shell = require ('./ssh2shell'),
SSH = new SSH2Shell(host1);

//default on end event handler used by all hosts
SSH.on ('end', function onEnd( sessionText, sshObj, self ) {
  console.log("\n-------------------------------------------------");
  console.log("Session text for " + sshObj.server.host + ":\n" + sessionText + "\nThe End\n\n");
});

//Start the process
SSH.connect();
```

Here's the output:
```
webmail.example.com: Connection.connect
Connected to Primary host1
webmail.example.com: Connection.ready
Running commands Now
webmail.example.com: Connection.shell
webmail.example.com: Normal prompt detected
webmail.example.com: Class.commandComplete
webmail.example.com: Next command: ls /
webmail.example.com: Normal prompt detected
webmail.example.com: Class.commandComplete
webmail.example.com: Queued hosts for this host
[ { server: 
     { host: 'mail.example.com',
       port: 22,
       userName: 'user',
       password: 'PASSWORD' },
    commands: [ 'whoami' ],
    debug: true,
    connectedMessage: 'Connected to host2',
    readyMessage: 'Running commands Now',
    closedMessage: 'Completed' } ]
webmail.example.com: SSH to mail.example.com
mail.example.com: Class.commandComplete
mail.example.com: Next command: mail.example.com: SSH -oStrictHostKeyChecking=no mrc
mail.example.com: Normal prompt detected
mail.example.com: Class.commandComplete
mail.example.com: Next command: whoami
mail.example.com: Normal prompt detected
mail.example.com: Class.commandComplete
mail.example.com: Queued exit commands: exit
mail.example.com: Next command: exit
mail.example.com: Stream.finish
mail.example.com: Class.end

-------------------------------------------------
Session text for mail.example.com:
undefinedmail.example.com: SSH -oStrictHostKeyChecking=no mrc
-bash: mail.example.com:: command not found
[root@webmail ~]# whoami
root
[root@webmail ~]# 
The End


mail.example.com: Stream.close
mail.example.com: Connection.close
Completed
mail.example.com: Class.commandTimeout
mail.example.com: Class.error
Timeout error: mail.example.com: Command timed out after 5 seconds
```

Am I doing anything wrong or is that a bug?

**Comment by cmp-202** [comment]
looks like a find replace error in code I will just fix it

**Comment by cmp-202** [comment]
Ok I have published that fix on npm so it should come though shortly or you can grab the code from master.

**Comment by MadsRC** [comment]
I just pulled the update, but I still get the same error:

```
webmail.example.com: Connection.connect
Connected to Primary host1
webmail.example.com: Connection.ready
Running commands Now
webmail.example.com: Connection.shell
webmail.example.com: Normal prompt detected
webmail.example.com: Class.commandComplete
webmail.example.com: Next command: ls /
webmail.example.com: Normal prompt detected
webmail.example.com: Class.commandComplete
webmail.example.com: Queued hosts for this host
[ { server: 
     { host: 'mail.example.com',
       port: 22,
       userName: 'user',
       password: 'PASSWORD' },
    commands: [ 'whoami' ],
    debug: true,
    connectedMessage: 'Connected to host2',
    readyMessage: 'Running commands Now',
    closedMessage: 'Completed' } ]
webmail.example.com: SSH to mail.example.com
mail.example.com: Class.commandComplete
mail.example.com: Next command: ssh -oStrictHostKeyChecking=no user@mail.example.com
mail.example.com: SSH password prompt
mail.example.com: Class.commandTimeout
mail.example.com: Class.error
Timeout error: mail.example.com: Command timed out after 5 seconds
mail.example.com: Connection.close
Completed
mail.example.com: Stream.finish
mail.example.com: Class.end

-------------------------------------------------
Session text for mail.example.com:
undefinedssh -oStrictHostKeyChecking=no user@mail.example.com
user@mail.example.com's password: 
Last login: Thu Sep 29 14:00:59 2016 from webmail.example.com
[user@mail]~% 
The End


mail.example.com: Stream.close
```

However, it does seem like it logs in to mail.example.com from webmail.example.com - So that part works fine.

**Comment by MadsRC** [comment]
Now that I take a closer look at it, it's not the same error.

**Comment by cmp-202** [comment]
hmm not sure what is undefined but it looks like it failed to respond to the password prompt.

**Comment by cmp-202** [comment]
I might need to setup multiple VM's and rerun the test file. What do you get if you turn on verbose as well.

**Comment by MadsRC** [comment]
No problem, just glad you have the time to look into it.

The output is:

```
webmail.example.com: Connection.connect
Connected to Primary host1
webmail.example.com: Connection.ready
Running commands Now
webmail.example.com: Connection.shell
webmail.example.com: Normal prompt detected
Last failed login: Thu Sep 29 08:51:57 EDT 2016 from 91.224.160.131 on ssh:notty
There were 12 failed login attempts since the last successful login.
Last login: Thu Sep 29 08:11:00 2016 from public-ip1.wwi.dk
[root@webmail ~]# 
webmail.example.com: Command complete: Response: Last failed login: Thu Sep 29 08:51:57 EDT 2016 from 91.224.160.131 on ssh:notty
There were 12 failed login attempts since the last successful login.
Last login: Thu Sep 29 08:11:00 2016 from public-ip1.wwi.dk
[root@webmail ~]# 
webmail.example.com: Next command: ls /
webmail.example.com: Normal prompt detected
ls /
bin   dev  home  lib  mnt   opt   root  sbin  sys  usr
boot  etc  lib   media  mnt  proc  run   srv   tmp  var
[root@webmail ~]# 
webmail.example.com: Command complete: Response: ls /
bin   dev  home  lib  mnt   opt   root  sbin  sys  usr
boot  etc  lib   media  mnt  proc  run   srv   tmp  var
[root@webmail ~]# 
webmail.example.com: Queued hosts for this host
[ { server: 
     { host: 'mail.example.com',
       port: 22,
       userName: 'user',
       password: '' },
    commands: [ 'whoami' ],
    connectedMessage: 'Connected to host2',
    readyMessage: 'Running commands Now',
    closedMessage: 'Completed',
    debug: true,
    verbose: true,
    onCommandComplete: [Function: onCommandComplete] } ]
webmail.example.com: SSH to mail.example.com

mail.example.com: Command complete: Response: 
mail.example.com: Next command: ssh -oStrictHostKeyChecking=no user@mail.example.com
mail.example.com: SSH password prompt
mail.example.com: Class.commandTimeout
mail.example.com: Timeout command: ssh -oStrictHostKeyChecking=no user@mail.example.com response: ssh -oStrictHostKeyChecking=no user@mail.example.com
user@mail.example.com's password: 
Last login: Thu Sep 29 14:11:12 2016 from webmail.example.com
[user@mail]~% 
mail.example.com: Class.error
Timeout error: mail.example.com: Command timed out after 5 seconds
mail.example.com: Connection.close
Completed
mail.example.com: Stream.finish
mail.example.com: Class.end

-------------------------------------------------
Session text for mail.example.com:
undefinedssh -oStrictHostKeyChecking=no user@mail.example.com
user@mail.example.com's password: 
Last login: Thu Sep 29 14:11:12 2016 from webmail.example.com
[user@mail]~% 
The End


mail.example.com: Stream.close
```

**Comment by cmp-202** [comment]
looks like it accepted the password but the next standard prompt wasn't detected. Got to `[user@mail]~% ` and timedout (bloody timeouts!).

**Comment by cmp-202** [comment]
Okay found the problem the next prompt test was a password prompt not a standard prompt. Just goes to show how many people use this functionality. Can you grab the lib/ssh2shell.js file from master and drop it into your node_modules/ssh2shell/lib folder and give it a try.

**Comment by MadsRC** [comment]
Unfortunately I get the same output.

You want the output again?

Sure it's a password prompt? From the logs on the server (and as the motd on server 2 also says) it seems that there's been a login from webmail.example.com on mail.example.com

**Comment by cmp-202** [comment]
I will have to get back to this tomorrow and run the test file to see if I can track it down.

**Comment by cmp-202** [comment]
So I finally worked it out. 

The timeout code was added after the initial tunneling code was finished. When connecting to new hosts a new sshObj is created and populated with default values and host object values that you define. Each sshObject has a timeout timer added to it (might not be the best idea) when a command is run. When that host is exited the timeout timer was not being cleared resulting timeout every time. 

I have rectified that and published to npm. Give it a try and see how you get on. Not sure if this affects your other problem.

**Comment by MadsRC** [comment]
It seems to work! Still had a problem detecting the prompt of the second machine (The user was using zsh instead of bash) - After changing to bash on the second machine, it worked like a charm.

A minor issue, which I don't know if you want in a separate issue, is that if the first host (webmail.example.com' only has 'msg:connected to jump host' in it's commands array, the following output is given:

```
Connected to Primary host1
Running commands Now
Last login: Fri Sep 30 02:11:43 2016 from public-ip1.wwi.dk
[root@webmail ~]# 

ssh -oStrictHostKeyChecking=no user@mail.example.com
user@mail.example.com's password: 
Last login: Fri Sep 30 08:10:40 2016 from webmail.example.com
[user@mail ~]$ 
whoami
user
er@mail ~]$ 
exit
logout
Connection to mail.example.dk closed.
[root@webmail ~]# 

-------------------------------------------------
Session text for mail.example.dk:
Connected to mail.example.dk
whoami
user
er@mail ~]$ 
The End




-------------------------------------------------
Session text for webmail.example.com:
Connected to webmail.example.com

The End


Completed
```

Seems like a minor issue however. Thank you for solving this so fast :D

**Comment by cmp-202** [comment]
Yeah lets do that as a new issue. My test failed with an exception so it needs some love.

**Comment by cmp-202** [comment]
I will create it.

**Comment by cmp-202** [comment]
The prompt detection regex chars can be changed in a host object to match different prompt requirements. I also think zsh can be set to output a different prompt for SSH connections if zsh funtionality was required over bash.

I will close this issue as resolved based on your result.
